Hepsi:Derle Calistir
Derle:
	g++ -I ./include -c ./src/Dugum.cpp -o ./lib/Dugum.o
	g++ -I ./include -c ./src/Iterator.cpp -o ./lib/Iterator.o
	g++ -I ./include -c ./src/LinkedList.cpp -o ./lib/LinkedList.o
	g++ -I ./include -c ./src/okumaIslemleri.cpp -o ./lib/okumaIslemleri.o
	g++ -I ./include -c ./src/Main.cpp -o ./lib/Main.o
	g++ ./lib/Dugum.o ./lib/Iterator.o ./lib/LinkedList.o ./lib/okumaIslemleri.o ./lib/Main.o -o ./bin/calistir.exe
Calistir:
	./bin/calistir